<?php
namespace Meisa\MenuBundle\Form\Type;

/**
 * Created by PhpStorm.
 * User: mohammed
 * Date: 05/12/14
 * Time: 06:24 م
 */
use Sonata\DoctrineORMAdminBundle\Admin\FieldDescription;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class MeisaLinkFieldType extends AbstractType{

    public function finishView(FormView $view, FormInterface $form, array $options)
    {
        parent::finishView($view, $form, $options); // TODO: Change the autogenerated stub
        $view->vars['attr']['class']=$view->vars['attr']['class'].' meisa_menu_link';
    }

    public function getParent()
    {
        return 'text';
    }

    public function getName()
    {
        return 'meisa_link';
    }
} 